In [1]:
import pandas as pd
import re

In [2]:
df=pd.read_csv('frauds.csv')

C:\Users\HAI\AppData\Local\Temp\ipykernel_14996\1449140172.py:1: DtypeWarning: Columns (1,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('frauds.csv')

In [3]:
df.columns = [re.sub(r';;;', '', col) for col in df.columns]
 
df = df.applymap(lambda x: re.sub(r';;;', '', str(x)) if isinstance(x, str) else x)

C:\Users\HAI\AppData\Local\Temp\ipykernel_14996\1339574411.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: re.sub(r';;;', '', str(x)) if isinstance(x, str) else x)

In [4]:
df.columns = [re.sub(r';;', '', col) for col in df.columns]
 
df = df.applymap(lambda x: re.sub(r';;', '', str(x)) if isinstance(x, str) else x)

C:\Users\HAI\AppData\Local\Temp\ipykernel_14996\3784443779.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: re.sub(r';;', '', str(x)) if isinstance(x, str) else x)

In [5]:
df.columns = [re.sub(r';', '', col) for col in df.columns]
 
df = df.applymap(lambda x: re.sub(r';', '', str(x)) if isinstance(x, str) else x)

C:\Users\HAI\AppData\Local\Temp\ipykernel_14996\1225933125.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: re.sub(r';', '', str(x)) if isinstance(x, str) else x)

In [6]:


# Rename columns to meaningful names
df.columns = [
    'record_id',               # Unnamed: 0
    'customer_number',         # NIS_RAD
    'fraud_case_number',       # NUM_FR
    'detection_date',          # F_DETEC
    'fraud_type',              # TIPO(TR.TIP_FRA)
    'fraud_observation',       # OBS_FRA
    'address_reference',       # REF_DIR
    'total_recovered_amount',  # IMP_TOT_REC
    'recovery_number',         # NUM_REC
    'account_status',          # ESTADO(RE.EST_ACT)
    'device_code',             # CODIGO(AP.CO_APARATO)
    'power_capacity_kw',       # POTENCIA
    'quantity',                # CANTIDAD
    'daily_usage_hours'        # HORAS_USO_DIA
]

 
print(df.head())

   record_id customer_number  fraud_case_number detection_date  \
0          0       200054854           200001.0     01/02/2011
1          1       200054854           200001.0     01/02/2011
2          2       200054854           200001.0     01/02/2011
3          3       200054854           200001.0     01/02/2011
4          4       200054854           200001.0     01/02/2011

                 fraud_type              fraud_observation address_reference  \
0  SHUNT AT METER TERMINALS   shunt aux bornes du compteur             DEIDO
1  SHUNT AT METER TERMINALS   shunt aux bornes du compteur             DEIDO
2  SHUNT AT METER TERMINALS   shunt aux bornes du compteur             DEIDO
3  SHUNT AT METER TERMINALS   shunt aux bornes du compteur             DEIDO
4  SHUNT AT METER TERMINALS   shunt aux bornes du compteur             DEIDO

   total_recovered_amount recovery_number       account_status  \
0                303244.0       221714517  POTENTIAL WRITE-OFF
1                303244.0       221714517  POTENTIAL WRITE-OFF
2                303244.0       221714517  POTENTIAL WRITE-OFF
3                303244.0       221714517  POTENTIAL WRITE-OFF
4                303244.0       221714517  POTENTIAL WRITE-OFF

                     device_code  power_capacity_kw  quantity  \
0  TELEVISEUR/VACUUM CLEANER/FAX              100.0       3.0
1                        DECODER              100.0       2.0
2                            FAN               75.0       3.0
3                           LAMP               60.0       6.0
4              REFRIGERATOR 250L              190.0       1.0

  daily_usage_hours
0                10
1                10
2                 6
3                 8
4                12

In [7]:
df.head()

,record_id,customer_number,fraud_case_number,detection_date,fraud_type,fraud_observation,address_reference,total_recovered_amount,recovery_number,account_status,device_code,power_capacity_kw,quantity,daily_usage_hours
0,0,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,TELEVISEUR/VACUUM CLEANER/FAX,100.0,3.0,10
1,1,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,DECODER,100.0,2.0,10
2,2,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,FAN,75.0,3.0,6
3,3,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,LAMP,60.0,6.0,8
4,4,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,REFRIGERATOR 250L,190.0,1.0,12

In [8]:
from sklearn.preprocessing import LabelEncoder
# Label encode each
le1 = LabelEncoder()
le2 = LabelEncoder()

df['fraud_type_encoded'] = le1.fit_transform(df['fraud_type'].astype(str))
df['fraud_obs_encoded'] = le2.fit_transform(df['fraud_observation'].astype(str))

# Combine numerically (e.g. weighted sum)
df['fraud_combined_feature'] = (
    df['fraud_type_encoded'] * 10 + df['fraud_obs_encoded']
)

In [9]:
df.head()

,record_id,customer_number,fraud_case_number,detection_date,fraud_type,fraud_observation,address_reference,total_recovered_amount,recovery_number,account_status,device_code,power_capacity_kw,quantity,daily_usage_hours,fraud_type_encoded,fraud_obs_encoded,fraud_combined_feature
0,0,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,TELEVISEUR/VACUUM CLEANER/FAX,100.0,3.0,10,42,1056,1476
1,1,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,DECODER,100.0,2.0,10,42,1056,1476
2,2,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,FAN,75.0,3.0,6,42,1056,1476
3,3,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,LAMP,60.0,6.0,8,42,1056,1476
4,4,200054854,200001.0,01/02/2011,SHUNT AT METER TERMINALS,shunt aux bornes du compteur,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,REFRIGERATOR 250L,190.0,1.0,12,42,1056,1476

In [10]:

df = df.drop(['fraud_obs_encoded'], axis=1)
df = df.drop(['fraud_type'], axis=1)
df = df.drop(['fraud_observation'], axis=1)

In [11]:
df.head()

,record_id,customer_number,fraud_case_number,detection_date,address_reference,total_recovered_amount,recovery_number,account_status,device_code,power_capacity_kw,quantity,daily_usage_hours,fraud_type_encoded,fraud_combined_feature
0,0,200054854,200001.0,01/02/2011,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,TELEVISEUR/VACUUM CLEANER/FAX,100.0,3.0,10,42,1476
1,1,200054854,200001.0,01/02/2011,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,DECODER,100.0,2.0,10,42,1476
2,2,200054854,200001.0,01/02/2011,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,FAN,75.0,3.0,6,42,1476
3,3,200054854,200001.0,01/02/2011,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,LAMP,60.0,6.0,8,42,1476
4,4,200054854,200001.0,01/02/2011,DEIDO,303244.0,221714517,POTENTIAL WRITE-OFF,REFRIGERATOR 250L,190.0,1.0,12,42,1476

In [12]:
df['device_power_feature'] = df['device_code'].astype(str) + ' | ' + df['power_capacity_kw'].astype(str)

In [13]:
df['device_power_feature']

0          TELEVISEUR/VACUUM CLEANER/FAX | 100.0
1                                DECODER | 100.0
2                                     FAN | 75.0
3                                    LAMP | 60.0
4                      REFRIGERATOR 250L | 190.0
                           ...
1048570         ORDINARY FLUORESCENT LAMP | 40.0
1048571                         COMPUTER | 200.0
1048572              FLOOD LIGHT (1*250W) | 40.0
1048573          AIR CONDITIONER 3.5 HP | 2600.0
1048574                 COMPRESSOR 4 HP | 3000.0
Name: device_power_feature, Length: 1048575, dtype: object

In [14]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Example df already loaded

# 1. Frequency encoding for device_code
device_freq = df['device_code'].value_counts(normalize=True)
df['device_code_freq'] = df['device_code'].map(device_freq)

# OR label encoding (if fewer unique values)
# le = LabelEncoder()
# df['device_code_encoded'] = le.fit_transform(df['device_code'].astype(str))

# 2. Fill missing numeric values if any
df['power_capacity_kw'] = df['power_capacity_kw'].fillna(df['power_capacity_kw'].median())
df['quantity'] = df['quantity'].fillna(df['quantity'].median())

# 3. Now these three features can be used directly in your ML model:
# - device_code_freq (or device_code_encoded)
# - power_capacity_kw
# - quantity

# Optional: Drop original 'device_code' if you want
df.drop('device_code', axis=1, inplace=True)

print(df[['device_code_freq', 'power_capacity_kw', 'quantity']].head())

   device_code_freq  power_capacity_kw  quantity
0          0.043924              100.0       3.0
1          0.044339              100.0       2.0
2          0.111470               75.0       3.0
3          0.095232               60.0       6.0
4          0.069041              190.0       1.0

In [15]:
# Example combining by multiplication (gives weight to all three)
df['combined_feature'] = df['device_code_freq'] * df['power_capacity_kw'] * df['quantity']

# Or, if you want to combine by weighted sum (adjust weights as needed)
# df['combined_feature'] = (df['device_code_freq'] * 0.5) + (df['power_capacity_kw'] * 0.3) + (df['quantity'] * 0.2)

print(df[['device_code_freq', 'power_capacity_kw', 'quantity', 'combined_feature']].head())

   device_code_freq  power_capacity_kw  quantity  combined_feature
0          0.043924              100.0       3.0         13.177335
1          0.044339              100.0       2.0          8.867881
2          0.111470               75.0       3.0         25.080750
3          0.095232               60.0       6.0         34.283621
4          0.069041              190.0       1.0         13.117848

In [16]:
df = df.drop(['device_code_freq'], axis=1)
df = df.drop(['power_capacity_kw'], axis=1)
df = df.drop(['quantity'], axis=1)

In [17]:
	 
df = df.drop(['device_power_feature'], axis=1)

In [18]:
df.rename(columns={'combined_feature': 'device_feature'}, inplace=True)

In [19]:
df = df.drop(['fraud_case_number'], axis=1)

In [20]:
df = df.drop(['address_reference'], axis=1)

In [21]:
df = df.drop(['recovery_number'], axis=1)

In [22]:
df.head()

,record_id,customer_number,detection_date,total_recovered_amount,account_status,daily_usage_hours,fraud_type_encoded,fraud_combined_feature,device_feature
0,0,200054854,01/02/2011,303244.0,POTENTIAL WRITE-OFF,10,42,1476,13.177335
1,1,200054854,01/02/2011,303244.0,POTENTIAL WRITE-OFF,10,42,1476,8.867881
2,2,200054854,01/02/2011,303244.0,POTENTIAL WRITE-OFF,6,42,1476,25.080750
3,3,200054854,01/02/2011,303244.0,POTENTIAL WRITE-OFF,8,42,1476,34.283621
4,4,200054854,01/02/2011,303244.0,POTENTIAL WRITE-OFF,12,42,1476,13.117848

In [23]:

df['account_status'].value_counts()

account_status
PAID UNDER INSTALMENT AGREEMENT                 287794
PAID                                            268568
POTENTIAL WRITE-OFF                             250368
SUSPENDED                                       116231
CANCELLED                                        66431
SENT TO CUSTOMER                                 42692
UNDER INSTALMENT AGREEMENT                       11685
BILLED                                            1764
MANUAL DEFINITE WRITE-OFF                         1263
SUSPENSION PROCESS DETAINED                        631
FINAL DEMAND LETTER                                499
CANCELLED DUE TO TRANSFER TO ANOTHER ACCOUNT       256
AUTOMATICALLY COLLECTED STAFF INVOICE               87
AUTOMATICALLY COLLECTED ZERO AMOUNT                 19
MANUAL POTENTIAL WRITE-OFF                          12
Name: count, dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
le1 = LabelEncoder()
df['account_status'] = le1.fit_transform(df['account_status'].astype(str))

In [26]:
df

,record_id,customer_number,detection_date,total_recovered_amount,account_status,daily_usage_hours,fraud_type_encoded,fraud_combined_feature,device_feature
0,0,200054854,01/02/2011,303244.0,10,10,42,1476,13.177335
1,1,200054854,01/02/2011,303244.0,10,10,42,1476,8.867881
2,2,200054854,01/02/2011,303244.0,10,6,42,1476,25.080750
3,3,200054854,01/02/2011,303244.0,10,8,42,1476,34.283621
4,4,200054854,01/02/2011,303244.0,10,12,42,1476,13.117848
...,...,...,...,...,...,...,...,...,...
1048570,1048570,203478691,04/06/2021,332013.0,8,6,45,46333,2.697014
1048571,1048571,203478691,04/06/2021,332013.0,8,8,45,46333,4.767338
1048572,1048572,203478691,04/06/2021,332013.0,8,6,45,46333,3.461032
1048573,1048573,201928138,04/06/2021,3868429.0,9,12,25,21072,3.566536
1048574,1048574,201928138,04/06/2021,3868429.0,9,12,25,21072,5.179815

In [27]:
df['usage_by_accounts']=df['account_status']*df['daily_usage_hours']

In [28]:
df.head()

,record_id,customer_number,detection_date,total_recovered_amount,account_status,daily_usage_hours,fraud_type_encoded,fraud_combined_feature,device_feature,usage_by_accounts
0,0,200054854,01/02/2011,303244.0,10,10,42,1476,13.177335,10101010101010101010
1,1,200054854,01/02/2011,303244.0,10,10,42,1476,8.867881,10101010101010101010
2,2,200054854,01/02/2011,303244.0,10,6,42,1476,25.080750,6666666666
3,3,200054854,01/02/2011,303244.0,10,8,42,1476,34.283621,8888888888
4,4,200054854,01/02/2011,303244.0,10,12,42,1476,13.117848,12121212121212121212

In [29]:
df = df.drop(['account_status'], axis=1)

In [30]:
 
df = df.drop(['daily_usage_hours'], axis=1)

In [31]:
df.head()

,record_id,customer_number,detection_date,total_recovered_amount,fraud_type_encoded,fraud_combined_feature,device_feature,usage_by_accounts
0,0,200054854,01/02/2011,303244.0,42,1476,13.177335,10101010101010101010
1,1,200054854,01/02/2011,303244.0,42,1476,8.867881,10101010101010101010
2,2,200054854,01/02/2011,303244.0,42,1476,25.080750,6666666666
3,3,200054854,01/02/2011,303244.0,42,1476,34.283621,8888888888
4,4,200054854,01/02/2011,303244.0,42,1476,13.117848,12121212121212121212

In [32]:
aggregated_df = df.groupby('detection_date')[df.select_dtypes(include=['number']).columns].mean().reset_index()
print(aggregated_df)

     detection_date      record_id  total_recovered_amount  \
0        01/01/2021  922289.947368           207306.631579
1        01/02/2011       3.000000           303244.000000
2        01/02/2012   82324.000000           328579.230216
3        01/02/2013  115759.500000           621781.480769
4        01/02/2016  154340.454545           359014.763636
...             ...            ...                     ...
2851     31/12/2016  171625.500000           605822.000000
2852     31/12/2018  195632.500000           419907.972222
2853     31/12/2019  305177.815578           455797.395189
2854     31/12/2020  819894.386379           158938.543549
2855      456457557  570074.500000                1.500000

      fraud_type_encoded  fraud_combined_feature  device_feature
0              26.526316            21958.947368       17.839747
1              42.000000             1476.000000       15.090503
2              27.884892            31048.517986       10.739098
3              38.769231            30408.250000       24.301390
4              18.854545            33809.181818       11.735724
...                  ...                     ...             ...
2851           24.000000            12477.000000       25.249591
2852            4.000000            24017.472222       12.095920
2853           28.129439            31558.627721       12.694267
2854           29.726261            24653.802881       12.900045
2855           34.000000            26948.400000             NaN

[2856 rows x 6 columns]

In [33]:
numeric_cols = df.select_dtypes(include=['number']).columns
aggregated_df = df.groupby(['detection_date', 'customer_number'])[numeric_cols].mean().reset_index()
print(aggregated_df)

       detection_date                                    customer_number  \
0          01/01/2021                                          203678475
1          01/01/2021                                          203679355
2          01/01/2021                                          203679368
3          01/01/2021                                          203679497
4          01/02/2011                                          200054854
...               ...                                                ...
211965     31/12/2020                                          203698561
211966     31/12/2020                                          203698589
211967     31/12/2020                                          203698598
211968     31/12/2020                                          203698654
211969      456457557  203410579#549892#23/06/2020#RACCORDEMENT DIREC...

        record_id  total_recovered_amount  fraud_type_encoded  \
0        922141.0                101010.0                36.0
1        922280.5                269313.0                 6.0
2        922305.5                101010.0                36.0
3        922363.5                269313.0                36.0
4             3.0                303244.0                42.0
...           ...                     ...                 ...
211965   819492.0                 28098.0                 4.0
211966   819528.0                 28098.0                 4.0
211967   819113.0                 63530.0                 4.0
211968   819498.0                224308.0                36.0
211969   570074.5                     1.5                34.0

        fraud_combined_feature  device_feature
0                      23218.0        9.742819
1                      19231.0       22.082147
2                      23218.0       16.831203
3                      23218.0       18.318174
4                       1476.0       15.090503
...                        ...             ...
211965                    40.0        8.360250
211966                    40.0        8.360250
211967                 17922.0        4.033101
211968                 37797.0       14.436053
211969                 26948.4             NaN

[211970 rows x 7 columns]

In [34]:
aggregated_df.head()

,detection_date,customer_number,record_id,total_recovered_amount,fraud_type_encoded,fraud_combined_feature,device_feature
0,01/01/2021,203678475,922141.0,101010.0,36.0,23218.0,9.742819
1,01/01/2021,203679355,922280.5,269313.0,6.0,19231.0,22.082147
2,01/01/2021,203679368,922305.5,101010.0,36.0,23218.0,16.831203
3,01/01/2021,203679497,922363.5,269313.0,36.0,23218.0,18.318174
4,01/02/2011,200054854,3.0,303244.0,42.0,1476.0,15.090503

In [35]:
fraud_type_mapping = {'customer_number':'SERVICE_NO'}
aggregated_df.rename(columns=fraud_type_mapping, inplace=True)

In [36]:
aggregated_df.head()

,detection_date,SERVICE_NO,record_id,total_recovered_amount,fraud_type_encoded,fraud_combined_feature,device_feature
0,01/01/2021,203678475,922141.0,101010.0,36.0,23218.0,9.742819
1,01/01/2021,203679355,922280.5,269313.0,6.0,19231.0,22.082147
2,01/01/2021,203679368,922305.5,101010.0,36.0,23218.0,16.831203
3,01/01/2021,203679497,922363.5,269313.0,36.0,23218.0,18.318174
4,01/02/2011,200054854,3.0,303244.0,42.0,1476.0,15.090503

In [37]:
aggregated_df.to_csv('agg.csv')

In [38]:
df1=pd.read_csv('customer_data.csv')

In [39]:
df1.head()

,PHASE,TARIFF,POWER_SUSCRIBED,TENSION,DIVISION,ACTIVITY_CMS,REGION,AGENCY,payment_mode,IsActive,Tenure_Days,Avg_Consumption,Max_Consumption,Total_Payment,Spike_Count,Has_inspected,inspection_count,fraud_found_category,Found_fraud,SERVICE_NBR
0,1- Phase,LV,2.2,LOW VOLTAGE( 220 ),DVC DOUALA CENTRE,Wholesale and Retail,DCUD,CSC_DEIDO,PREPAID,1,7702,106.0680,182.2,452480.00,4,1,1,0,0,200050294
1,1- Phase,LV,1.1,LOW VOLTAGE( 220 ),DVC DOUALA CENTRE,Wholesale and Retail,DCUD,CSC_DEIDO,PREPAID,1,7702,47.8907,69.0,262025.00,1,1,1,0,0,200050392
2,1- Phase,LV,1.1,LOW VOLTAGE( 220 ),DVC DOUALA CENTRE,Wholesale and Retail,DCUD,CSC_DEIDO,PREPAID,1,7702,9.9000,10.0,1995.05,0,1,1,1,1,200050477
3,1- Phase,LV,2.2,LOW VOLTAGE( 220 ),DVC DOUALA CENTRE,Dwelling House,DCUD,CSC_DEIDO,PREPAID,1,7553,81.7500,110.0,163500.00,5,1,1,0,0,200050502
4,1- Phase,LV,2.2,LOW VOLTAGE( 220 ),DVC DOUALA CENTRE,Dwelling House,DCUD,CSC_DEIDO,PREPAID,1,5636,142.7880,195.2,508596.00,8,1,1,1,1,200050562

In [40]:
fraud_type_mapping = {'SERVICE_NBR':'SERVICE_NO'}
df1.rename(columns=fraud_type_mapping, inplace=True)

In [62]:
df9 = pd.merge(aggregated_df, df1, how='inner', on='SERVICE_NO')

In [63]:
df9

,detection_date,SERVICE_NO,record_id,total_recovered_amount,fraud_type_encoded,fraud_combined_feature,device_feature,PHASE,TARIFF,POWER_SUSCRIBED,...,IsActive,Tenure_Days,Avg_Consumption,Max_Consumption,Total_Payment,Spike_Count,Has_inspected,inspection_count,fraud_found_category,Found_fraud
0,03/08/2011,200290337,39118.0,618930.0,46.0,46216.0,10.190110,3 - Phase,LV,6.6,...,1,5586,225.2920,332.0,832999.00,2,1,1,1,1
1,03/09/2012,200224386,109505.5,134630.0,4.0,40.0,5.288949,1- Phase,LV,2.2,...,1,7702,32.6667,40.0,9800.00,0,1,1,1,1
2,05/09/2011,200193825,45642.5,193205.0,14.0,140.0,11.772540,1- Phase,LV,2.2,...,0,6439,139.2220,200.5,343386.00,3,1,1,1,1
3,05/10/2011,200207041,51087.0,252830.0,42.0,420.0,9.377192,1- Phase,LV,2.2,...,1,5050,100.6900,120.0,146000.00,4,1,1,0,0
4,06/07/2011,200195367,26470.5,511261.0,21.0,210.0,12.632604,1- Phase,LV,2.2,...,1,7424,183.2060,226.1,1611970.00,2,1,1,0,0
5,07/04/2011,200249985,721.5,469524.0,14.0,29422.0,28.956226,1- Phase,LV,2.2,...,1,7702,112.0880,176.3,233487.00,5,1,1,1,1
6,08/06/2011,200278721,15825.0,303244.0,46.0,43354.0,6.910706,1- Phase,LV,2.2,...,1,7702,176.0600,219.5,995590.00,3,1,1,1,1
7,08/06/2011,200700543,14979.0,217055.0,46.0,43315.0,14.769209,1- Phase,LV,2.2,...,1,5737,139.8450,169.4,157485.00,1,1,1,1,1
8,09/11/2011,200703447,63573.0,279394.0,42.0,46593.0,5.293076,1- Phase,LV,2.2,...,1,7702,75.4545,114.0,41500.00,0,1,1,1,1
9,10/06/2011,200701831,16140.5,303244.0,46.0,43315.0,16.836224,1- Phase,LV,2.2,...,1,6254,40.0000,40.0,4000.00,0,1,1,1,1
10,13/02/2012,200293626,85001.5,641597.0,4.0,40.0,15.818522,3 - Phase,LV,13.2,...,1,5925,198.3000,255.7,455007.00,2,1,1,1,1
11,13/07/2011,200342604,29060.5,451636.0,15.0,51861.0,15.250645,1- Phase,LV,2.2,...,1,7702,106.8980,171.1,372013.00,3,1,1,1,1
12,14/10/2011,200349188,54596.5,475486.0,22.0,220.0,7.753667,1- Phase,LV,1.1,...,1,7702,85.9000,100.0,85900.00,0,1,1,1,1
13,15/06/2011,200268510,17741.5,314125.0,46.0,43315.0,8.645342,1- Phase,LV,1.1,...,1,7702,15.0222,19.8,13704.10,1,1,1,1,1
14,16/10/2012,200707988,113237.0,314125.0,15.0,29500.0,16.044274,1- Phase,LV,2.2,...,1,5490,131.9470,199.4,131550.00,2,1,1,1,1
15,19/10/2011,200349188,56065.5,475486.0,31.0,18192.0,7.798828,1- Phase,LV,1.1,...,1,7702,85.9000,100.0,85900.00,0,1,1,1,1
16,20/02/2012,200084792,86620.0,200458.0,17.0,21525.0,6.480742,1- Phase,LV,2.2,...,1,7702,57.5000,70.0,23000.00,2,1,1,1,1
17,20/06/2013,200251200,124785.0,245366.0,19.0,29727.0,11.704409,1- Phase,LV,2.2,...,1,6055,160.0850,202.6,453495.00,0,1,1,0,0
18,22/01/2013,200286880,115334.5,134630.0,42.0,420.0,7.707641,1- Phase,LV,6.6,...,1,5757,22.8000,22.8,5397.32,0,1,1,1,1
19,22/07/2011,200083366,33851.0,217055.0,42.0,420.0,10.907561,1- Phase,LV,2.2,...,1,5595,128.7930,196.0,389031.00,6,1,1,1,1
20,23/08/2011,200293534,44406.0,217055.0,46.0,46216.0,11.796836,1- Phase,LV,8.8,...,1,5079,67.3417,80.0,121101.00,1,1,1,1,1
21,27/05/2011,200241026,10090.5,303244.0,42.0,43275.0,34.050223,1- Phase,LV,3.3,...,1,7702,297.9840,426.1,3184960.00,6,1,1,1,1
22,29/04/2013,200253094,120645.0,686506.0,27.0,3301.0,20.933426,1- Phase,LV,2.2,...,1,7702,352.5110,474.6,564999.00,3,1,1,0,0
23,30/06/2011,200277801,24145.5,339019.0,31.0,51662.0,8.164400,3 - Phase,LV,6.6,...,1,5330,105.3240,181.8,172355.00,3,1,1,1,1
24,30/11/2011,200283083,68625.5,85537.0,19.0,28724.0,4.746801,1- Phase,LV,2.2,...,1,6922,81.4610,117.8,565973.00,5,1,1,1,1

In [64]:
df9.fillna(method='ffill', inplace=True)
df9.fillna(method='bfill', inplace=True)

C:\Users\HAI\AppData\Local\Temp\ipykernel_14996\3664550700.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df9.fillna(method='ffill', inplace=True)
C:\Users\HAI\AppData\Local\Temp\ipykernel_14996\3664550700.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df9.fillna(method='ffill', inplace=True)
C:\Users\HAI\AppData\Local\Temp\ipykernel_14996\3664550700.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df9.fillna(method='bfill', inplace=True)

In [70]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols_to_encode = ['PHASE', 'TARIFF', 'TENSION', 'DIVISION', 'ACTIVITY_CMS', 'REGION', 'AGENCY', 'payment_mode']

for col in cols_to_encode:
    df9[col] = le.fit_transform(df9[col].astype(str))

In [71]:
df9.loc[0]

detection_date            03/08/2011
SERVICE_NO                 200290337
record_id                    39118.0
total_recovered_amount      618930.0
fraud_type_encoded              46.0
fraud_combined_feature       46216.0
device_feature              10.19011
PHASE                              1
TARIFF                             0
POWER_SUSCRIBED                  6.6
TENSION                            1
DIVISION                           1
ACTIVITY_CMS                       0
REGION                             0
AGENCY                             8
payment_mode                       1
IsActive                           1
Tenure_Days                     5586
Avg_Consumption              225.292
Max_Consumption                332.0
Total_Payment               832999.0
Spike_Count                        2
Has_inspected                      1
inspection_count                   1
fraud_found_category               1
Found_fraud                        1
Name: 0, dtype: object

In [72]:
from sklearn.preprocessing import StandardScaler

# Columns to exclude
exclude_cols = ['detection_date', 'SERVICE_NO','Found_fraud']

# Columns to scale (all except exclude_cols)
cols_to_scale = [col for col in df9.columns if col not in exclude_cols]

# Initialize scaler
scaler = StandardScaler()

# Fit and transform
df9[cols_to_scale] = scaler.fit_transform(df9[cols_to_scale])

# Final check
print(df9.head())

  detection_date  SERVICE_NO  record_id  total_recovered_amount  \
0     03/08/2011   200290337  -0.412150                1.765719
1     03/09/2012   200224386   1.450738               -1.250169
2     05/09/2011   200193825  -0.239472               -0.885404
3     05/10/2011   200207041  -0.095377               -0.514100
4     06/07/2011   200195367  -0.746882                1.095231

   fraud_type_encoded  fraud_combined_feature  device_feature     PHASE  \
0            1.147418                1.068705       -0.316252  2.708013
1           -1.783942               -1.241718       -1.019809 -0.369274
2           -1.085999               -1.236715       -0.089096 -0.369274
3            0.868241               -1.222705       -0.432946 -0.369274
4           -0.597439               -1.233212        0.034365 -0.369274

   TARIFF  POWER_SUSCRIBED  ...  IsActive  Tenure_Days  Avg_Consumption  \
0     0.0         1.166548  ...  0.204124    -1.089795         1.255480
1     0.0        -0.409868  ...  0.204124     0.990311        -1.153249
2     0.0        -0.409868  ... -4.898979    -0.251264         0.179197
3     0.0        -0.409868  ...  0.204124    -1.616702        -0.302635
4     0.0        -0.409868  ...  0.204124     0.717027         0.729206

   Max_Consumption  Total_Payment  Spike_Count  Has_inspected  \
0         1.439981       0.586425    -0.084629            0.0
1        -1.159070      -0.642011    -1.142489            0.0
2         0.269518      -0.144210     0.444301            0.0
3        -0.447001      -0.438763     0.973232            0.0
4         0.497380       1.748860    -0.084629            0.0

   inspection_count  fraud_found_category  Found_fraud
0               0.0              0.436436            1
1               0.0              0.436436            1
2               0.0              0.436436            1
3               0.0             -2.291288            0
4               0.0             -2.291288            0

[5 rows x 26 columns]

In [73]:
df9.head()

,detection_date,SERVICE_NO,record_id,total_recovered_amount,fraud_type_encoded,fraud_combined_feature,device_feature,PHASE,TARIFF,POWER_SUSCRIBED,...,IsActive,Tenure_Days,Avg_Consumption,Max_Consumption,Total_Payment,Spike_Count,Has_inspected,inspection_count,fraud_found_category,Found_fraud
0,03/08/2011,200290337,-0.412150,1.765719,1.147418,1.068705,-0.316252,2.708013,0.0,1.166548,...,0.204124,-1.089795,1.255480,1.439981,0.586425,-0.084629,0.0,0.0,0.436436,1
1,03/09/2012,200224386,1.450738,-1.250169,-1.783942,-1.241718,-1.019809,-0.369274,0.0,-0.409868,...,0.204124,0.990311,-1.153249,-1.159070,-0.642011,-1.142489,0.0,0.0,0.436436,1
2,05/09/2011,200193825,-0.239472,-0.885404,-1.085999,-1.236715,-0.089096,-0.369274,0.0,-0.409868,...,-4.898979,-0.251264,0.179197,0.269518,-0.144210,0.444301,0.0,0.0,0.436436,1
3,05/10/2011,200207041,-0.095377,-0.514100,0.868241,-1.222705,-0.432946,-0.369274,0.0,-0.409868,...,0.204124,-1.616702,-0.302635,-0.447001,-0.438763,0.973232,0.0,0.0,-2.291288,0
4,06/07/2011,200195367,-0.746882,1.095231,-0.597439,-1.233212,0.034365,-0.369274,0.0,-0.409868,...,0.204124,0.717027,0.729206,0.497380,1.748860,-0.084629,0.0,0.0,-2.291288,0

In [85]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, roc_auc_score
from lazypredict.Supervised import LazyClassifier
 
 

# Separate features and target
X = df9.drop(columns=['Found_fraud'])
y = df9['Found_fraud']

# Encode categorical columns
cat_cols = X.select_dtypes(include=['object']).columns
le = LabelEncoder()
for col in cat_cols:
    X[col] = le.fit_transform(X[col].astype(str))

# Scale numeric features
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, stratify=y, random_state=42
)

# LazyPredict Benchmarking
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

print(models)

  0%|          | 0/32 [00:00<?, ?it/s]

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Number of positive: 17, number of negative: 3
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 20, number of used features: 0
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.850000 -> initscore=1.734601
[LightGBM] [Info] Start training from score 1.734601
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
                               Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model
AdaBoostClassifier                 1.00               1.00     1.00      1.00
BaggingClassifier                  1.00               1.00     1.00      1.00
DecisionTreeClassifier             1.00               1.00     1.00      1.00
GaussianNB                         1.00               1.00     1.00      1.00
ExtraTreesClassifier               1.00               1.00     1.00      1.00
ExtraTreeClassifier                1.00               1.00     1.00      1.00
LinearSVC                          1.00               1.00     1.00      1.00
LinearDiscriminantAnalysis         1.00               1.00     1.00      1.00
LabelSpreading                     1.00               1.00     1.00      1.00
LabelPropagation                   1.00               1.00     1.00      1.00
QuadraticDiscriminantAnalysis      1.00               1.00     1.00      1.00
RidgeClassifier                    1.00               1.00     1.00      1.00
RidgeClassifierCV                  1.00               1.00     1.00      1.00
SGDClassifier                      1.00               1.00     1.00      1.00
LogisticRegression                 1.00               1.00     1.00      1.00
NearestCentroid                    1.00               1.00     1.00      1.00
PassiveAggressiveClassifier        1.00               1.00     1.00      1.00
Perceptron                         1.00               1.00     1.00      1.00
KNeighborsClassifier               0.80               0.50     0.50      0.71
BernoulliNB                        0.80               0.50     0.50      0.71
CalibratedClassifierCV             0.80               0.50     0.50      0.71
DummyClassifier                    0.80               0.50     0.50      0.71
RandomForestClassifier             0.80               0.50     0.50      0.71
SVC                                0.80               0.50     0.50      0.71
XGBClassifier                      0.80               0.50     0.50      0.71
LGBMClassifier                     0.80               0.50     0.50      0.71

                               Time Taken
Model
AdaBoostClassifier                   0.03
BaggingClassifier                    0.04
DecisionTreeClassifier               0.02
GaussianNB                           0.01
ExtraTreesClassifier                 0.11
ExtraTreeClassifier                  0.01
LinearSVC                            0.02
LinearDiscriminantAnalysis           0.02
LabelSpreading                       0.02
LabelPropagation                     0.03
QuadraticDiscriminantAnalysis        0.02
RidgeClassifier                      0.02
RidgeClassifierCV                    0.05
SGDClassifier                        0.05
LogisticRegression                   0.02
NearestCentroid                      0.01
PassiveAggressiveClassifier          0.02
Perceptron                           0.02
KNeighborsClassifier                 0.55
BernoulliNB                          0.02
CalibratedClassifierCV               0.04
DummyClassifier                      0.01
RandomForestClassifier               0.14
SVC                                  0.03
XGBClassifier                        0.08
LGBMClassifier                       0.03

In [69]:
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Print columns to verify what you have
print("Columns in DataFrame:")
print(df9.columns.tolist())

target_col = 'Found_fraud'
cols_to_drop = ['Found_fraud', 'detection_date', 'SERVICE_NO']

# Check if target column exists
if target_col not in df9.columns:
    raise KeyError(f"Target column '{target_col}' not found in DataFrame columns.")

# Prepare target variable
y = df9[target_col]

# Drop only existing columns from df for features
existing_cols_to_drop = [col for col in cols_to_drop if col in df.columns]
X = df9.drop(existing_cols_to_drop, axis=1)

# Standard Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Initialize and fit XGBClassifier
model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Columns in DataFrame:
['detection_date', 'SERVICE_NO', 'record_id', 'total_recovered_amount', 'fraud_type_encoded', 'fraud_combined_feature', 'device_feature', 'PHASE', 'TARIFF', 'POWER_SUSCRIBED', 'TENSION', 'DIVISION', 'ACTIVITY_CMS', 'REGION', 'AGENCY', 'payment_mode', 'IsActive', 'Tenure_Days', 'Avg_Consumption', 'Max_Consumption', 'Total_Payment', 'Spike_Count', 'Has_inspected', 'inspection_count', 'fraud_found_category', 'Found_fraud']

ValueError: could not convert string to float: '3 - Phase'

In [60]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier
import numpy as np

# Define parameter grid to sample from
param_dist = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.3, 0.5],
    'reg_alpha': [0, 0.1, 0.5],
    'reg_lambda': [1, 1.5, 2]
}

# Initialize model
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

# Setup RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=30,  # number of parameter settings that are sampled
    scoring='roc_auc',  # or 'accuracy', 'average_precision'
    cv=3,  # 3-fold cross-validation
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# Fit RandomizedSearchCV on training data
random_search.fit(X_train, y_train)

# Best parameters
print("Best parameters found: ", random_search.best_params_)

# Best estimator
best_model = random_search.best_estimator_

# Evaluate on test set
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

from sklearn.metrics import accuracy_score, roc_auc_score, classification_report
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Test ROC AUC:", roc_auc_score(y_test, y_proba))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Fitting 3 folds for each of 30 candidates, totalling 90 fits

C:\Users\HAI\AppData\Roaming\Python\Python313\site-packages\xgboost\training.py:183: UserWarning: [13:30:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters found:  {'subsample': 0.6, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.1, 'colsample_bytree': 1.0}
Test Accuracy: 1.0
Test ROC AUC: 1.0

Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       796
         1.0       1.00      1.00      1.00     41794

    accuracy                           1.00     42590
   macro avg       1.00      1.00      1.00     42590
weighted avg       1.00      1.00      1.00     42590

In [61]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report
from xgboost import XGBClassifier

# Assuming df is your DataFrame and 'Found_fraud' is your target column
target_col = 'Found_fraud'

# Check if target column exists
if target_col not in df9.columns:
    raise KeyError(f"Target column '{target_col}' not found in DataFrame columns.")

# Prepare target variable
y = df9[target_col]

# Drop columns not useful for modeling (make sure they exist)
cols_to_drop = ['Found_fraud', 'detection_date', 'SERVICE_NO']
existing_cols = [col for col in cols_to_drop if col in df9.columns]
X = df9.drop(existing_cols, axis=1)

# Standard scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Stratified train-test split to maintain class balance
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# Define hyperparameter search space for XGBClassifier
param_dist = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.3, 0.5],
    'reg_alpha': [0, 0.5, 1, 1.5],
    'reg_lambda': [1, 1.5, 2, 3]
}

# Initialize XGBClassifier
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

# Randomized Search CV
random_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=30,
    scoring='roc_auc',
    cv=3,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

# Fit hyperparameter search
random_search.fit(X_train, y_train)

print("Best parameters found: ", random_search.best_params_)

# Train the best model on the full training set
best_model = random_search.best_estimator_

# Predict on test set
y_pred = best_model.predict(X_test)
y_pred_proba = best_model.predict_proba(X_test)[:, 1]

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Test Accuracy: {accuracy:.4f}")
print(f"Test ROC AUC: {roc_auc:.4f}")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

C:\Users\HAI\AppData\Roaming\Python\Python313\site-packages\xgboost\training.py:183: UserWarning: [13:31:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters found:  {'subsample': 0.6, 'reg_lambda': 1.5, 'reg_alpha': 0, 'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0.1, 'colsample_bytree': 0.8}
Test Accuracy: 1.0000
Test ROC AUC: 1.0000
Confusion Matrix:
 [[  811     0]
 [    0 41779]]
Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       811
         1.0       1.00      1.00      1.00     41779

    accuracy                           1.00     42590
   macro avg       1.00      1.00      1.00     42590
weighted avg       1.00      1.00      1.00     42590